services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build: .
    command: ["python", "worker.py"]
    depends_on:
      - rabbitmq
    env_file:
      - .env
